### ISSUE TITLE
Notes in the pdf sheet are always printed void

### ISSUE THREAD

**Issue by D3m1urg0** [anathema/anathema#379]
as per the object,

i dont know if these "note box" is supposed to print the "note" value from anathema or is a simple "write here by your hand" but i wanted to print info from the character sheet in there (ex. merits and flaw list, or artifact/permanent charms modified movement and jump distances and so on)

**Comment by UrsKR** [comment]
Please check that the Platform_FX project depends on ``jfxrt.jar`` and exports that dependency.
To do so, select the project in the project explorer (usually on the left hand of the screen) and select properties from the context menu (at the very bottom, IIRC).
There, you can check the java build path - is the file mentioned there? If not, add it - it's part of your JDK starting from JDK 7u6 forward.
Once it's there, you need to tell eclipse to export the file to all dependencies - do so on the order and export tab by checking the file in the list.

Please report back when you tried it.

**Comment by D3m1urg0** [comment]
it should be all as you said without i had to do nothing..
that's what i found:
https://www.dropbox.com/s/2w5oqko6zr3nqk7/platform_fx.png?dl=0
https://www.dropbox.com/s/9dpba6mnnphdpav/orderandexport.png?dl=0

PS: i also noticed that after the java 8 upgrade anathema itself (the tool) wont work

it suggests to close the application at startup

**Comment by UrsKR** [comment]
That's odd. I am running Windows, not Ubuntu, so I cannot reproduce your scenario exactly; in other words: "It works on my machine."

For the classpath(?) issue, please check two things: First, from a terminal in the directory where you cloned the code, run ``./gradlew clean build``. This will build a distribution of Anathema using your local JDK. If this doesn't work either, we can rule out eclipse as the root cause.
Second, please check that Eclipse can actually discover the missing JavaFX classes. In eclipse, press CTRL+SHIFT+T, and type "Bounds" into the "find type" dialog. Does it show you the ``javafx.geometry.Bounds`` class?

As for Anathema itself not running, please launch it from a terminal (``java -jar anathema.jar``) and post the exception.

@smattox, are you still using eclipse? Do you remember any hoops to jump through while setting up for development?

**Comment by D3m1urg0** [comment]
when i try to build:
```
murphy@mervyn:~/sviluppo/anathema$ ./gradlew clean build

FAILURE: Build failed with an exception.

* Where:
Script '/home/murphy/sviluppo/anathema/gradle/copyDependencies.gradle' line: 16

* What went wrong:
Could not resolve all dependencies for configuration ':Campaign_Scribe:compile'.
> Could not find com.miglayout:miglayout-core:5.0-SNAPSHOT.
  Required by:
      anathema:Campaign_Scribe:unspecified > anathema:Platform:unspecified
> Could not find com.miglayout:miglayout-javafx:5.0-SNAPSHOT.
  Required by:
      anathema:Campaign_Scribe:unspecified > anathema:Platform_FX:unspecified
```
Eclypse shows me the `javafx.geometry.Bounds` class

And that's what i get when i run anathema in a java 8 instead of java 7 enviornment:

```
murphy@mervyn:~/Dropbox/Gdr/char-gen/anathema5.13$ java -jar anathema.jar
Loading JavaFX from /usr/lib/jvm/java-8-oracle/jre/lib/jfxrt.jar
20:56:28.168 [main] INFO  net.sf.anathema.Anathema - Launching Anathema
20:56:35.493 [AWT-EventQueue-0] INFO  org.reflections.Reflections - Reflections took 1924 ms to scan 63 urls, producing 1005 keys and 1279 values 
20:56:36.776 [AWT-EventQueue-0] INFO  n.s.a.initialization.GuiInitializer - Program version is 5.1.3
20:56:36.956 [AWT-EventQueue-0] INFO  n.s.a.c.g.f.DataSetInitializer - Charms: Found 454 data files.
20:56:39.681 [AWT-EventQueue-0] INFO  n.s.a.c.g.f.DataSetInitializer - Spells: Found 2 data files.
20:56:39.759 [AWT-EventQueue-0] INFO  n.s.a.c.g.f.DataSetInitializer - CharacterTemplateExtensions: Found 105 data files.
20:56:39.818 [AWT-EventQueue-0] INFO  n.s.a.c.g.f.DataSetInitializer - CharacterTemplates: Found 35 data files.
20:56:42.061 [AWT-EventQueue-0] INFO  n.s.a.c.p.bootjob.RepositoryCleanup - Found repository at version 5.1.3.
20:56:42.062 [AWT-EventQueue-0] INFO  n.s.a.c.p.bootjob.RepositoryCleanup - No update necessary.
20:56:45.096 [AWT-EventQueue-0] ERROR n.s.a.f.s.SwingDialogExceptionHandler - Uncaught Exception
java.lang.ExceptionInInitializerError: null
	at net.sf.anathema.fx.character.perspective.CharacterGridFxView.<init>(CharacterGridFxView.java:26) ~[character_main_fx.jar:na]
	at net.sf.anathema.swing.character.perspective.CharacterSystemView.<init>(CharacterSystemView.java:15) ~[character_main_swing.jar:na]
	at net.sf.anathema.character.platform.module.perspective.CharacterSystemPerspective.initContent(CharacterSystemPerspective.java:32) ~[character_main_impl.jar:na]
	at net.sf.anathema.framework.view.perspective.PerspectiveStack.add(PerspectiveStack.java:23) ~[platform_swing.jar:na]
	at net.sf.anathema.framework.view.perspective.PerspectivePaneFactory.createContent(PerspectivePaneFactory.java:32) ~[platform_swing.jar:na]
	at net.sf.anathema.framework.view.SwingApplicationFrame.createContentPane(SwingApplicationFrame.java:72) ~[platform_swing.jar:na]
	at net.sf.anathema.framework.view.SwingApplicationFrame.show(SwingApplicationFrame.java:38) ~[platform_swing.jar:na]
	at net.sf.anathema.Anathema$1.run(Anathema.java:45) ~[platform_swing.jar:na]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[na:1.8.0_25]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744) ~[na:1.8.0_25]
	at java.awt.EventQueue.access$400(EventQueue.java:97) ~[na:1.8.0_25]
	at java.awt.EventQueue$3.run(EventQueue.java:697) ~[na:1.8.0_25]
	at java.awt.EventQueue$3.run(EventQueue.java:691) ~[na:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_25]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[na:1.8.0_25]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714) ~[na:1.8.0_25]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_25]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_25]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_25]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_25]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_25]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_25]
Caused by: java.lang.IllegalStateException: Toolkit not initialized
	at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:270) ~[jfxrt.jar:na]
	at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:265) ~[jfxrt.jar:na]
	at com.sun.javafx.application.PlatformImpl.setPlatformUserAgentStylesheet(PlatformImpl.java:540) ~[jfxrt.jar:na]
	at com.sun.javafx.application.PlatformImpl.setDefaultPlatformUserAgentStylesheet(PlatformImpl.java:502) ~[jfxrt.jar:na]
	at javafx.scene.control.Control.<clinit>(Control.java:87) ~[jfxrt.jar:na]
	... 22 common frames omitted
20:56:45.098 [AWT-EventQueue-0] ERROR n.s.a.f.s.SwingDialogExceptionHandler - 
java.lang.ExceptionInInitializerError: null
	at net.sf.anathema.fx.character.perspective.CharacterGridFxView.<init>(CharacterGridFxView.java:26) ~[character_main_fx.jar:na]
	at net.sf.anathema.swing.character.perspective.CharacterSystemView.<init>(CharacterSystemView.java:15) ~[character_main_swing.jar:na]
	at net.sf.anathema.character.platform.module.perspective.CharacterSystemPerspective.initContent(CharacterSystemPerspective.java:32) ~[character_main_impl.jar:na]
	at net.sf.anathema.framework.view.perspective.PerspectiveStack.add(PerspectiveStack.java:23) ~[platform_swing.jar:na]
	at net.sf.anathema.framework.view.perspective.PerspectivePaneFactory.createContent(PerspectivePaneFactory.java:32) ~[platform_swing.jar:na]
	at net.sf.anathema.framework.view.SwingApplicationFrame.createContentPane(SwingApplicationFrame.java:72) ~[platform_swing.jar:na]
	at net.sf.anathema.framework.view.SwingApplicationFrame.show(SwingApplicationFrame.java:38) ~[platform_swing.jar:na]
	at net.sf.anathema.Anathema$1.run(Anathema.java:45) ~[platform_swing.jar:na]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[na:1.8.0_25]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744) ~[na:1.8.0_25]
	at java.awt.EventQueue.access$400(EventQueue.java:97) ~[na:1.8.0_25]
	at java.awt.EventQueue$3.run(EventQueue.java:697) ~[na:1.8.0_25]
	at java.awt.EventQueue$3.run(EventQueue.java:691) ~[na:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_25]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[na:1.8.0_25]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714) ~[na:1.8.0_25]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_25]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_25]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_25]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_25]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_25]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_25]
Caused by: java.lang.IllegalStateException: Toolkit not initialized
	at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:270) ~[jfxrt.jar:na]
	at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:265) ~[jfxrt.jar:na]
	at com.sun.javafx.application.PlatformImpl.setPlatformUserAgentStylesheet(PlatformImpl.java:540) ~[jfxrt.jar:na]
	at com.sun.javafx.application.PlatformImpl.setDefaultPlatformUserAgentStylesheet(PlatformImpl.java:502) ~[jfxrt.jar:na]
	at javafx.scene.control.Control.<clinit>(Control.java:87) ~[jfxrt.jar:na]
	... 22 common frames omitted
```

Then an alert says me: "Severe error: it's recomended that the program is closed, do you want to quit? (yes closes, no does nothing but wont start anathema)

**Comment by smattox** [comment]
I do use Eclipse, yes.

I don't recall which ones specifically off hand, but I do remember that
there are two unit test classes related to Scribe which throw up
compilation errors. I have to have them commented out on my local build.

-Sean

**Comment by UrsKR** [comment]
@D3m1urg0, thanks for trying all of these.
Regarding the first, the gradle build, please pull the latest update and try again. 
A post-christmas update to the MigLayout library removed the snapshot version and I fixed our dependencies just yesterday.

As for the launch error, I will pull out my old Linux setup and try to get the error myself.

**Comment by D3m1urg0** [comment]
Thank you for providing all this help and that awesome Tool at the first.
I just tried and can confirm that the launch error is the same also in
windows8.1 when i upgrade to java8

Il giorno dom 4 gen 2015 09:33 AM Urs Reupke <notifications@github.com> ha
scritto:
