### ISSUE TITLE
Crashes after upgrading to OS X 10.11 El Capitan

### ISSUE THREAD

**Issue by dorward** [anathema/anathema#382]
After upgrading to El Capitan, Anathema complains about running about of memory and the UI displays a "It is recommended that the program is closed. Do you want to quit?" message and doesn't load the character database.

[ MacOS ][ david@raston ] %  ./JavaAppLauncher
Loading JavaFX from /Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar
10:19:32.907 [main] INFO  net.sf.anathema.Anathema - Launching Anathema
10:19:34.466 [AWT-EventQueue-0] INFO  org.reflections.Reflections - Reflections took 820 ms to scan 63 urls, producing 1005 keys and 1279 values
10:19:34.726 [AWT-EventQueue-0] INFO  n.s.a.initialization.GuiInitializer - Program version is 5.1.3
10:19:34.800 [AWT-EventQueue-0] INFO  n.s.a.c.g.f.DataSetInitializer - Spells: Found 2 data files.
10:19:34.907 [AWT-EventQueue-0] INFO  n.s.a.c.g.f.DataSetInitializer - CharacterTemplates: Found 35 data files.
10:19:34.972 [AWT-EventQueue-0] INFO  n.s.a.c.g.f.DataSetInitializer - Charms: Found 454 data files.
10:19:36.757 [AWT-EventQueue-0] INFO  n.s.a.c.g.f.DataSetInitializer - CharacterTemplateExtensions: Found 105 data files.
10:19:37.427 [AWT-EventQueue-0] INFO  n.s.a.c.p.bootjob.RepositoryCleanup - Found repository at version 5.1.3.
10:19:37.428 [AWT-EventQueue-0] INFO  n.s.a.c.p.bootjob.RepositoryCleanup - No update necessary.
Exception in runnable
java.lang.ExceptionInInitializerError
    at com.sun.javafx.scene.control.skin.ScrollPaneSkin.computeScrollNodeSize(ScrollPaneSkin.java:872)
    at com.sun.javafx.scene.control.skin.ScrollPaneSkin.layoutChildren(ScrollPaneSkin.java:753)
    at javafx.scene.Parent.layout(Parent.java:1018)
    at javafx.scene.Parent.layout(Parent.java:1028)
    at javafx.scene.Scene.layoutDirtyRoots(Scene.java:516)
    at javafx.scene.Scene.doLayoutPass(Scene.java:487)
    at javafx.scene.Scene.preferredSize(Scene.java:1489)
    at javafx.scene.Scene.impl_preferredSize(Scene.java:1516)
    at javafx.stage.Window$9.invalidated(Window.java:716)
    at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:127)
    at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:161)
    at javafx.stage.Window.setShowing(Window.java:779)
    at javafx.stage.Window.show(Window.java:794)
    at com.sun.javafx.stage.EmbeddedWindow.show(EmbeddedWindow.java:57)
    at javafx.embed.swing.JFXPanel.setSceneImpl(JFXPanel.java:278)
    at javafx.embed.swing.JFXPanel.setScene(JFXPanel.java:245)
    at net.sf.anathema.platform.fx.InitScene.run(InitScene.java:22)
    at com.sun.javafx.application.PlatformImpl$4$1.run(PlatformImpl.java:179)
    at com.sun.javafx.application.PlatformImpl$4$1.run(PlatformImpl.java:176)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl$4.run(PlatformImpl.java:176)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:76)
Caused by: java.lang.NullPointerException
    at com.sun.t2k.MacFontFinder.initPSFontNameToPathMap(MacFontFinder.java:339)
    at com.sun.t2k.MacFontFinder.getFontNamesOfFontFamily(MacFontFinder.java:390)
    at com.sun.t2k.T2KFontFactory.getFontResource(T2KFontFactory.java:232)
    at com.sun.t2k.LogicalFont.getSlot0Resource(LogicalFont.java:184)
    at com.sun.t2k.LogicalFont.getSlotResource(LogicalFont.java:228)
    at com.sun.t2k.CompositeStrike.getStrikeSlot(CompositeStrike.java:86)
    at com.sun.t2k.CompositeStrike.getMetrics(CompositeStrike.java:132)
    at com.sun.javafx.font.PrismFontUtils.getFontMetrics(PrismFontUtils.java:31)
    at com.sun.javafx.font.PrismFontLoader.getFontMetrics(PrismFontLoader.java:451)
    at javafx.scene.text.Text.<init>(Text.java:153)
    at com.sun.javafx.scene.control.skin.Utils.<clinit>(Utils.java:52)
    ... 22 more
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve 'last-color' while resolving lookups for '-fx-background-color' from rule '_.scroll-title' in stylesheet jar:file:/Applications/Anathema.app/Contents/Java/campaign_scribe.jar!/skin/anathema/scribe.css
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-text-inner-color' while resolving lookups for '-fx-text-fill' from rule '_.text-field' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-accent' while resolving lookups for '-fx-highlight-fill' from rule '_.text-input' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-shadow-highlight-color' while resolving lookups for '-fx-background-color' from rule '_.text-area' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-text-inner-color' while resolving lookups for '-fx-text-fill' from rule '_.text-input' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-control-inner-background' while resolving lookups for '-fx-prompt-text-fill' from rule '_.text-area' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-accent' while resolving lookups for '-fx-highlight-fill' from rule '_.text-input' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-box-border' while resolving lookups for '-fx-background-color' from rule '_.scroll-bar:vertical' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-box-border' while resolving lookups for '-fx-background-color' from rule '_.scroll-bar:vertical *.track-background' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-box-border' while resolving lookups for '-fx-background-color' from rule '_.scroll-bar _.increment-button' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-mark-highlight-color' while resolving lookups for '-fx-background-color' from rule '_.scroll-bar:vertical _.increment-arrow' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-box-border' while resolving lookups for '-fx-background-color' from rule '_.scroll-bar _.decrement-button' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-mark-highlight-color' while resolving lookups for '-fx-background-color' from rule '_.scroll-bar:vertical _.decrement-arrow' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-box-border' while resolving lookups for '-fx-background-color' from rule '_.scroll-bar:vertical _.track' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-box-border' while resolving lookups for '-fx-background-color' from rule '_.scroll-bar:vertical _.thumb' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-box-border' while resolving lookups for '-fx-background-color' from rule '_.scroll-bar:horizontal' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-box-border' while resolving lookups for '-fx-background-color' from rule '_.scroll-bar:horizontal *.track-background' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-box-border' while resolving lookups for '-fx-background-color' from rule '_.scroll-bar _.increment-button' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-mark-highlight-color' while resolving lookups for '-fx-background-color' from rule '_.scroll-bar:horizontal _.increment-arrow' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-box-border' while resolving lookups for '-fx-background-color' from rule '_.scroll-bar _.decrement-button' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-mark-highlight-color' while resolving lookups for '-fx-background-color' from rule '_.scroll-bar:horizontal _.decrement-arrow' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-box-border' while resolving lookups for '-fx-background-color' from rule '_.scroll-bar:horizontal _.track' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-box-border' while resolving lookups for '-fx-background-color' from rule '_.scroll-bar:horizontal _.thumb' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-box-border' while resolving lookups for '-fx-background-color' from rule '_.scroll-pane _.corner' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve 'last-color' while resolving lookups for '-fx-background-color' from rule '_.scroll-title' in stylesheet jar:file:/Applications/Anathema.app/Contents/Java/campaign_scribe.jar!/skin/anathema/scribe.css
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-text-inner-color' while resolving lookups for '-fx-text-fill' from rule '_.text-field' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-accent' while resolving lookups for '-fx-highlight-fill' from rule '_.text-input' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-box-border' while resolving lookups for '-fx-background-color' from rule '_.scroll-bar:vertical' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-box-border' while resolving lookups for '-fx-background-color' from rule '_.scroll-bar:vertical _.track-background' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-box-border' while resolving lookups for '-fx-background-color' from rule '_.scroll-bar _.increment-button' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-mark-highlight-color' while resolving lookups for '-fx-background-color' from rule '_.scroll-bar:vertical _.increment-arrow' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-box-border' while resolving lookups for '-fx-background-color' from rule '_.scroll-bar _.decrement-button' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-mark-highlight-color' while resolving lookups for '-fx-background-color' from rule '_.scroll-bar:vertical _.decrement-arrow' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-box-border' while resolving lookups for '-fx-background-color' from rule '_.scroll-bar:vertical _.track' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-box-border' while resolving lookups for '-fx-background-color' from rule '_.scroll-bar:vertical *.thumb' in stylesheet jar:file:/Applications/Anathema.app/Contents/PlugIns/jre1.7.0_21/Contents/Home/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
java.lang.NoClassDefFoundError: Could not initialize class com.sun.javafx.scene.control.skin.Utils
    at com.sun.javafx.scene.control.skin.LabeledSkinBase.computePrefWidth(LabeledSkinBase.java:749)
    at javafx.scene.Parent.prefWidth(Parent.java:867)
    at javafx.scene.layout.Region.prefWidth(Region.java:1368)
    at javafx.scene.control.Control.computePrefWidth(Control.java:852)
    at javafx.scene.Parent.prefWidth(Parent.java:867)
    at javafx.scene.control.Control.prefWidth(Control.java:722)
    at javafx.scene.Node.autosize(Node.java:2610)
    at javafx.scene.Parent.layoutChildren(Parent.java:1048)
    at org.tbee.javafx.scene.layout.MigPane.layoutChildren(Unknown Source)
    at javafx.scene.Parent.layout(Parent.java:1018)
    at javafx.scene.Parent.layout(Parent.java:1028)
    at javafx.scene.Parent.layout(Parent.java:1028)
    at javafx.scene.Parent.layout(Parent.java:1028)
    at javafx.scene.Scene.layoutDirtyRoots(Scene.java:516)
    at javafx.scene.Scene.doLayoutPass(Scene.java:487)
    at javafx.scene.Scene.access$3900(Scene.java:170)
    at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2203)
    at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:363)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:460)
    at com.sun.javafx.tk.quantum.QuantumToolkit$9.run(QuantumToolkit.java:329)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:76)
10:19:40.902 [AWT-EventQueue-0] ERROR n.s.a.f.s.SwingDialogExceptionHandler - Uncaught Exception
java.lang.OutOfMemoryError: Java heap space
    at java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75) ~[na:1.7.0_21]
    at java.awt.image.Raster.createPackedRaster(Raster.java:470) ~[na:1.7.0_21]
    at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032) ~[na:1.7.0_21]
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:338) ~[na:1.7.0_21]
    at javafx.embed.swing.JFXPanel.resizePixels(JFXPanel.java:574) ~[jfxrt.jar:na]
    at javafx.embed.swing.JFXPanel.processComponentEvent(JFXPanel.java:463) ~[jfxrt.jar:na]
    at java.awt.Component.processEvent(Component.java:6285) ~[na:1.7.0_21]
    at java.awt.Container.processEvent(Container.java:2229) ~[na:1.7.0_21]
    at java.awt.Component.dispatchEventImpl(Component.java:4861) ~[na:1.7.0_21]
    at java.awt.Container.dispatchEventImpl(Container.java:2287) ~[na:1.7.0_21]
    at java.awt.Component.dispatchEvent(Component.java:4687) ~[na:1.7.0_21]
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:729) ~[na:1.7.0_21]
    at java.awt.EventQueue.access$200(EventQueue.java:103) ~[na:1.7.0_21]
    at java.awt.EventQueue$3.run(EventQueue.java:688) ~[na:1.7.0_21]
    at java.awt.EventQueue$3.run(EventQueue.java:686) ~[na:1.7.0_21]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_21]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.7.0_21]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87) ~[na:1.7.0_21]
    at java.awt.EventQueue$4.run(EventQueue.java:702) ~[na:1.7.0_21]
    at java.awt.EventQueue$4.run(EventQueue.java:700) ~[na:1.7.0_21]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_21]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.7.0_21]
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:699) ~[na:1.7.0_21]
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242) [na:1.7.0_21]
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161) [na:1.7.0_21]
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150) [na:1.7.0_21]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146) [na:1.7.0_21]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138) [na:1.7.0_21]
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91) [na:1.7.0_21]
10:19:40.903 [AWT-EventQueue-0] ERROR n.s.a.f.s.SwingDialogExceptionHandler -
java.lang.OutOfMemoryError: Java heap space
    at java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75) ~[na:1.7.0_21]
    at java.awt.image.Raster.createPackedRaster(Raster.java:470) ~[na:1.7.0_21]
    at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032) ~[na:1.7.0_21]
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:338) ~[na:1.7.0_21]
    at javafx.embed.swing.JFXPanel.resizePixels(JFXPanel.java:574) ~[jfxrt.jar:na]
    at javafx.embed.swing.JFXPanel.processComponentEvent(JFXPanel.java:463) ~[jfxrt.jar:na]
    at java.awt.Component.processEvent(Component.java:6285) ~[na:1.7.0_21]
    at java.awt.Container.processEvent(Container.java:2229) ~[na:1.7.0_21]
    at java.awt.Component.dispatchEventImpl(Component.java:4861) ~[na:1.7.0_21]
    at java.awt.Container.dispatchEventImpl(Container.java:2287) ~[na:1.7.0_21]
    at java.awt.Component.dispatchEvent(Component.java:4687) ~[na:1.7.0_21]
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:729) ~[na:1.7.0_21]
    at java.awt.EventQueue.access$200(EventQueue.java:103) ~[na:1.7.0_21]
    at java.awt.EventQueue$3.run(EventQueue.java:688) ~[na:1.7.0_21]
    at java.awt.EventQueue$3.run(EventQueue.java:686) ~[na:1.7.0_21]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_21]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.7.0_21]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87) ~[na:1.7.0_21]
    at java.awt.EventQueue$4.run(EventQueue.java:702) ~[na:1.7.0_21]
    at java.awt.EventQueue$4.run(EventQueue.java:700) ~[na:1.7.0_21]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_21]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.7.0_21]
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:699) ~[na:1.7.0_21]
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242) [na:1.7.0_21]
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161) [na:1.7.0_21]
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150) [na:1.7.0_21]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146) [na:1.7.0_21]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138) [na:1.7.0_21]
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91) [na:1.7.0_21]
10:19:41.220 [AWT-EventQueue-0] ERROR n.s.a.f.s.SwingDialogExceptionHandler - Uncaught Exception
java.lang.OutOfMemoryError: Java heap space
    at java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75) ~[na:1.7.0_21]
    at java.awt.image.Raster.createPackedRaster(Raster.java:470) ~[na:1.7.0_21]
    at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032) ~[na:1.7.0_21]
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:338) ~[na:1.7.0_21]
    at javafx.embed.swing.JFXPanel.resizePixels(JFXPanel.java:574) ~[jfxrt.jar:na]
    at javafx.embed.swing.JFXPanel.processComponentEvent(JFXPanel.java:463) ~[jfxrt.jar:na]
    at java.awt.Component.processEvent(Component.java:6285) ~[na:1.7.0_21]
    at java.awt.Container.processEvent(Container.java:2229) ~[na:1.7.0_21]
    at java.awt.Component.dispatchEventImpl(Component.java:4861) ~[na:1.7.0_21]
    at java.awt.Container.dispatchEventImpl(Container.java:2287) ~[na:1.7.0_21]
    at java.awt.Component.dispatchEvent(Component.java:4687) ~[na:1.7.0_21]
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:729) ~[na:1.7.0_21]
    at java.awt.EventQueue.access$200(EventQueue.java:103) ~[na:1.7.0_21]
    at java.awt.EventQueue$3.run(EventQueue.java:688) ~[na:1.7.0_21]
    at java.awt.EventQueue$3.run(EventQueue.java:686) ~[na:1.7.0_21]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_21]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.7.0_21]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87) ~[na:1.7.0_21]
    at java.awt.EventQueue$4.run(EventQueue.java:702) ~[na:1.7.0_21]
    at java.awt.EventQueue$4.run(EventQueue.java:700) ~[na:1.7.0_21]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_21]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.7.0_21]
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:699) ~[na:1.7.0_21]
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242) ~[na:1.7.0_21]
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161) ~[na:1.7.0_21]
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:154) ~[na:1.7.0_21]
    at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:182) ~[na:1.7.0_21]
    at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:221) ~[na:1.7.0_21]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_21]
    at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:219) ~[na:1.7.0_21]
    at java.awt.Dialog.show(Dialog.java:1082) ~[na:1.7.0_21]
    at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:870) ~[na:1.7.0_21]
10:19:41.222 [AWT-EventQueue-0] ERROR n.s.a.f.s.SwingDialogExceptionHandler -
java.lang.OutOfMemoryError: Java heap space
    at java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75) ~[na:1.7.0_21]
    at java.awt.image.Raster.createPackedRaster(Raster.java:470) ~[na:1.7.0_21]
    at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032) ~[na:1.7.0_21]
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:338) ~[na:1.7.0_21]
    at javafx.embed.swing.JFXPanel.resizePixels(JFXPanel.java:574) ~[jfxrt.jar:na]
    at javafx.embed.swing.JFXPanel.processComponentEvent(JFXPanel.java:463) ~[jfxrt.jar:na]
    at java.awt.Component.processEvent(Component.java:6285) ~[na:1.7.0_21]
    at java.awt.Container.processEvent(Container.java:2229) ~[na:1.7.0_21]
    at java.awt.Component.dispatchEventImpl(Component.java:4861) ~[na:1.7.0_21]
    at java.awt.Container.dispatchEventImpl(Container.java:2287) ~[na:1.7.0_21]
    at java.awt.Component.dispatchEvent(Component.java:4687) ~[na:1.7.0_21]
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:729) ~[na:1.7.0_21]
    at java.awt.EventQueue.access$200(EventQueue.java:103) ~[na:1.7.0_21]
    at java.awt.EventQueue$3.run(EventQueue.java:688) ~[na:1.7.0_21]
    at java.awt.EventQueue$3.run(EventQueue.java:686) ~[na:1.7.0_21]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_21]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.7.0_21]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87) ~[na:1.7.0_21]
    at java.awt.EventQueue$4.run(EventQueue.java:702) ~[na:1.7.0_21]
    at java.awt.EventQueue$4.run(EventQueue.java:700) ~[na:1.7.0_21]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_21]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.7.0_21]
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:699) ~[na:1.7.0_21]
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242) ~[na:1.7.0_21]
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161) ~[na:1.7.0_21]
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:154) ~[na:1.7.0_21]
    at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:182) ~[na:1.7.0_21]
    at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:221) ~[na:1.7.0_21]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_21]
    at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:219) ~[na:1.7.0_21]
    at java.awt.Dialog.show(Dialog.java:1082) ~[na:1.7.0_21]
    at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:870) ~[na:1.7.0_21]
[ /Applications/Anathema.app/Contents/MacOS ]

**Comment by dorward** [comment]
Looks like I might have been running the previous version. Installing the newest seems to have fixed the issue … although my database seems to have gone.
